import os
from dotenv import load_dotenv

# Load .env
load_dotenv()

# Load PATHs for data preprocessing
RAW_DATA_PATH = os.getenv('RAW_DATA_PATH')
SAVE_PATH = os.getenv('SAVE_PATH')

# PATHs for experiments
DATA_PATH = os.getenv('DATA_PATH')
DE_PREDICTION_PATH = os.getenv('DE_PREDICTION_PATH')
DE_RESULTS_PATH = os.getenv('DE_RESULTS_PATH')

GPR_PREDICTION_PATH = os.getenv('GPR_PREDICTION_PATH')
GPR_RESULTS_PATH = os.getenv('GPR_RESULTS_PATH')

MCD_PREDICTION_PATH = os.getenv('MCD_PREDICTION_PATH')
MCD_RESULTS_PATH = os.getenv('MCD_RESULTS_PATH')

NGB_PREDICTION_PATH = os.getenv('NGB_PREDICTION_PATH')
NGB_RESULTS_PATH = os.getenv('NGB_RESULTS_PATH')

# Validate loaded PATHS
if not all([RAW_DATA_PATH, SAVE_PATH, DATA_PATH, DE_PREDICTION_PATH, DE_RESULTS_PATH, GPR_PREDICTION_PATH, 
            GPR_RESULTS_PATH, MCD_PREDICTION_PATH, MCD_RESULTS_PATH, 
            NGB_PREDICTION_PATH, NGB_RESULTS_PATH]):
    raise ValueError("Bitte .env-Datei mit RAW_DATA_PATH, SAVE_PATH, DATA_PATH, DE_PREDICTION_PATH, DE_RESULTS_PATH, GPR_PREDICTION_PATH, GPR_RESULTS_PATH, MCD_PREDICTION_PATH, MCD_RESULTS_PATH, NGB_PREDICTION_PATH, NGB_RESULTS_PATH erstellen!")